baseURL = 'https://my-website-2ne.pages.dev/'
languageCode = 'ja-jp'
title = '北澤茉奈のホームページ'
theme = 'PaperMod'

hasCJKLanguage = true

# タクソノミー（キーワード自動集計）の設定を明示
[taxonomies]
  category = "categories"
  tag = "tags"
  keyword = "keywords"

[params]
  env = "production"
  defaultTheme = "auto"
  disableThemeToggle = false
  paginate = 1
  dateFormat = "2006-1-2"

[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'Information'
  url = '/information/'
  weight = 2

[[menu.main]]
  name = 'Profile'
  url = '/profile/'
  weight = 3

[[menu.main]]
  name = 'Day Log'
  url = '/day-log/'
  weight = 4

[[menu.main]]
  name = 'Keywords'
  url = '/keywords/'
  weight = 5

[[menu.main]]
  name = 'Book Log'
  url = '/book-log/'
  weight = 6

[[menu.main]]
  name = 'Search'
  url = '/search/'
  weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]